[package]
name = "rust_lib_flutter_rust_ndk_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.32"
uuid = { version = "1.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["clock"] }
