// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.34.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// The type `CONNECTION` is not used by any `pub` functions, thus it is ignored.
// The type `CachedConnection` is not used by any `pub` functions, thus it is ignored.
// The type `CustomError` is not used by any `pub` functions, thus it is ignored.

Future<void> createTaskInDb(
        {required String title,
        required String subtitle,
        required Priority priority,
        dynamic hint}) =>
    RustLib.instance.api.crateApiModelPersistenceCreateTaskInDb(
        title: title, subtitle: subtitle, priority: priority, hint: hint);

Future<List<Task>> readAllTasksFromDb({dynamic hint}) =>
    RustLib.instance.api.crateApiModelPersistenceReadAllTasksFromDb(hint: hint);

Future<Task?> readTaskFromDb({required UuidValue taskId, dynamic hint}) =>
    RustLib.instance.api
        .crateApiModelPersistenceReadTaskFromDb(taskId: taskId, hint: hint);

Future<void> updateTaskInDb(
        {required UuidValue taskId,
        required String title,
        required String subtitle,
        required Priority priority,
        required bool isCompleted,
        dynamic hint}) =>
    RustLib.instance.api.crateApiModelPersistenceUpdateTaskInDb(
        taskId: taskId,
        title: title,
        subtitle: subtitle,
        priority: priority,
        isCompleted: isCompleted,
        hint: hint);

Future<void> deleteTaskFromDb({required UuidValue taskId, dynamic hint}) =>
    RustLib.instance.api
        .crateApiModelPersistenceDeleteTaskFromDb(taskId: taskId, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<rusqlite :: Error>>
@sealed
class RusqliteError extends RustOpaque {
  RusqliteError.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  RusqliteError.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RusqliteError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RusqliteError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RusqliteErrorPtr,
  );
}
