// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.34.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'model_persistence.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

List<Task> tasksByCompletion({required bool isCompleted, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimpleTasksByCompletion(isCompleted: isCompleted, hint: hint);

List<Task> tasksByPriority({required Priority priority, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimpleTasksByPriority(priority: priority, hint: hint);

void createTask(
        {required String taskTitle,
        required String taskSubtitle,
        required Priority taskPriority,
        dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleCreateTask(
        taskTitle: taskTitle,
        taskSubtitle: taskSubtitle,
        taskPriority: taskPriority,
        hint: hint);

List<Task> readAllTasks({dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleReadAllTasks(hint: hint);

Task? readTask({required UuidValue taskId, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleReadTask(taskId: taskId, hint: hint);

void updateTask(
        {required UuidValue taskId,
        required String title,
        required String subtitle,
        required Priority priority,
        required bool isCompleted,
        dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleUpdateTask(
        taskId: taskId,
        title: title,
        subtitle: subtitle,
        priority: priority,
        isCompleted: isCompleted,
        hint: hint);

void deleteTask({required UuidValue taskId, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleDeleteTask(taskId: taskId, hint: hint);
